/**
 * Renders the `config.yaml` that `agent-commerce init` writes, with no prompts or IO.
 *
 * The output is the raw document `parseConfig` accepts (`resources` keyed by
 * id, with `backend`/`expose`/`payments`/`input`/`output`), not the normalized
 * `CommerceResource` shape (`handler`/`exposedVia`/`paymentMethods`/...) that
 * `loadConfig()` returns.
 *
 * The facilitator key and merchant address are Anvil's public dev accounts #0
 * and #1. Never fund them. They come from `ANVIL_WELL_KNOWN_ACCOUNTS`, the list
 * the local deploy engine and the dev-key guard also read, because a
 * hand-copied or truncated literal breaks every paid request and slips past
 * the guard. The MockUSDC `asset` is a labeled placeholder: its address exists
 * only once `npm run chain:deploy` writes `.deploy/local.json`, and config
 * rejects the zero address.
 */

import { stringify } from 'yaml';
// Narrow module, not the `testing.ts` barrel: see manifest-env.ts
import { ANVIL_WELL_KNOWN_ACCOUNTS } from '../../payments/x402/local-chain/accounts';

/** Anvil account #1: the merchant settlement destination, never the facilitator */
export const LOCAL_DEV_MERCHANT_ADDRESS = ANVIL_WELL_KNOWN_ACCOUNTS[1].address;
/** Anvil account #0: the local facilitator signer, which settles on the dev chain only */
export const LOCAL_DEV_FACILITATOR_PRIVATE_KEY = ANVIL_WELL_KNOWN_ACCOUNTS[0].privateKey;
/** Placeholder only - replace with the MockUSDC address from `.deploy/local.json` */
export const PLACEHOLDER_ASSET_ADDRESS = '0x000000000000000000000000000000000000dEaD';

export type InitResourceChoice = 'weather' | 'report';
export type InitProtocolChoice = 'http' | 'mcp';

export interface InitAnswers {
  readonly backendBaseUrl: string;
  readonly resources: readonly InitResourceChoice[];
  readonly protocols: readonly InitProtocolChoice[];
  readonly x402Enabled: boolean;
  readonly merchantPayTo: string;
}

export function defaultInitAnswers(): InitAnswers {
  return {
    backendBaseUrl: 'http://localhost:3000',
    resources: ['weather', 'report'],
    protocols: ['http', 'mcp'],
    x402Enabled: true,
    merchantPayTo: LOCAL_DEV_MERCHANT_ADDRESS,
  };
}

function buildResourcesMap(answers: InitAnswers): Record<string, unknown> {
  const resources: Record<string, unknown> = {};
  const expose = [...answers.protocols];

  if (answers.resources.includes('weather')) {
    resources.weather = {
      name: 'Get weather',
      description: 'Deterministic demo weather lookup (free resource).',
      input: {
        type: 'object',
        properties: { city: { type: 'string' } },
        required: ['city'],
        additionalProperties: false,
      },
      backend: {
        type: 'http',
        method: 'GET',
        url: `${answers.backendBaseUrl}/api/weather/{city}`,
      },
      pricing: { type: 'free' },
      expose,
    };
  }

  if (answers.resources.includes('report')) {
    const paid = answers.x402Enabled;
    resources.report = {
      name: 'Get market report',
      description: 'Deterministic demo premium market report.',
      // No caller-supplied fields. Config loads a missing `input` as this same
      // closed schema; writing it out shows that in the generated file
      input: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      backend: {
        type: 'http',
        method: 'GET',
        url: `${answers.backendBaseUrl}/api/report`,
      },
      pricing: paid ? { type: 'fixed', amount: '0.01', currency: 'USDC' } : { type: 'free' },
      expose,
      ...(paid ? { payments: ['x402'] } : {}),
    };
  }

  return resources;
}

/** Builds the raw config object accepted by `parseConfig` (src/config) */
export function buildInitConfigObject(answers: InitAnswers): Record<string, unknown> {
  return {
    version: 1,
    merchant: {
      id: 'demo-merchant',
      name: 'Demo Merchant',
      publicBaseUrl: 'http://localhost:8080',
    },
    server: { port: 8080, host: '127.0.0.1' },
    storage: { receipts: { driver: 'sqlite', path: './data/receipts.db' } },
    protocols: {
      http: { enabled: answers.protocols.includes('http') },
      mcp: { enabled: answers.protocols.includes('mcp'), mountPath: '/mcp' },
    },
    resources: buildResourcesMap(answers),
    payments: answers.x402Enabled
      ? {
          x402: {
            enabled: true,
            network: 'eip155:84532',
            rpcUrl: 'http://127.0.0.1:8545',
            asset: PLACEHOLDER_ASSET_ADDRESS,
            assetName: 'MockUSDC',
            assetVersion: '2',
            assetDecimals: 6,
            payTo: answers.merchantPayTo,
            maxTimeoutSeconds: 60,
            facilitator: { mode: 'local', signerPrivateKey: LOCAL_DEV_FACILITATOR_PRIVATE_KEY },
          },
        }
      : {},
  };
}

const HEADER = `# Generated by \`agent-commerce init\`.
#
# With x402 enabled, the facilitator signerPrivateKey is Anvil's public dev
# account #0 and the default payTo is account #1.
# LOCAL DEVELOPMENT ONLY - DO NOT FUND: never use them outside a local chain.
# payments.x402.asset is a placeholder, not a real contract. Before running
# against the local chain, run \`npm run chain:deploy\` and set it to the
# MockUSDC address in \`.deploy/local.json\`. Before pointing this at a funded
# network, set \`payments.x402.payTo\` to your own settlement address.
#
# server.host is loopback (127.0.0.1): binding every interface should be a
# deliberate edit.
#
# server.adminToken and server.allowedOrigins are left unset, so no secret
# lands in a file you might commit. Without a token the operator routes
# (/api/receipts, /api/events) return 404. They serve the merchant's commerce
# ledger: payer addresses, amounts and settlement hashes. To enable them, add
# these keys to the server block below:
#   server:
#     adminToken: \${ADMIN_TOKEN}
#     allowedOrigins:
#       - http://localhost:5173
# See SECURITY.md before exposing this gateway beyond localhost.
`;

export function renderInitConfigYaml(answers: InitAnswers): string {
  const body = stringify(buildInitConfigObject(answers), { indent: 2 });
  return `${HEADER}\n${body}`;
}
