import { existsSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';
import { defaultOutputPath, runImportOpenApi } from '../../../src/cli/commands/import-openapi.js';
import { createCapturingIo } from '../../../src/cli/lib/io.js';
import { buildProgram } from '../../../src/cli/program.js';

const fixture = (name: string): string =>
  join(fileURLToPath(new URL('../openapi/fixtures/', import.meta.url)), name);

function tmpOutput(name = 'out.yaml'): string {
  return join(mkdtempSync(join(tmpdir(), 'agent-commerce-import-')), name);
}

async function run(options: Parameters<typeof runImportOpenApi>[0]) {
  const io = createCapturingIo();
  const code = await runImportOpenApi(options, io);
  return { code, io, out: io.out.join('\n'), err: io.err.join('\n') };
}

describe('agent-commerce import openapi', () => {
  it('appears in --help with its options', async () => {
    const io = createCapturingIo();
    const program = buildProgram(io);
    await expect(
      program.parseAsync(['node', 'agent-commerce', 'import', 'openapi', '--help']),
    ).rejects.toThrow();
    const help = io.out.join('\n');
    expect(help).toContain('--base-url');
    expect(help).toContain('--operation');
    expect(help).toContain('--tag');
    expect(help).toContain('--free');
    expect(help).toContain('--expose');
    expect(help).toContain('--strict');
    expect(help).toContain('--json');
  });

  it('imports a YAML document and writes a reviewable fragment', async () => {
    const output = tmpOutput();
    const { code, out } = await run({ source: fixture('responses-3.1.yaml'), output });

    expect(code).toBe(0);
    expect(out).toContain('Imported: 5');
    expect(out).toContain('Pricing/exposure were not inferred.');
    const written = readFileSync(output, 'utf8');
    expect(written).toContain('# Generated by agent-commerce import openapi');
    const parsed = parseYaml(written) as { resources: Record<string, unknown> };
    expect(Object.keys(parsed.resources)).toContain('getOrder');
  });

  it('imports a JSON document', async () => {
    const output = tmpOutput();
    const { code } = await run({ source: fixture('minimal-3.1.json'), output });
    expect(code).toBe(0);
    expect(readFileSync(output, 'utf8')).toContain('list_things:');
  });

  it('defaults the output name to <source>.agent-commerce.yaml', () => {
    expect(defaultOutputPath('./specs/openapi.yaml')).toBe('openapi.agent-commerce.yaml');
    expect(defaultOutputPath('/tmp/petstore.json')).toBe('petstore.agent-commerce.yaml');
  });

  it('refuses to overwrite an existing file, and leaves it untouched', async () => {
    const output = tmpOutput();
    writeFileSync(output, 'keep me\n', 'utf8');

    const { code, err } = await run({ source: fixture('responses-3.1.yaml'), output });

    expect(code).toBe(1);
    expect(err).toContain('already exists');
    expect(readFileSync(output, 'utf8')).toBe('keep me\n');
  });

  it('overwrites with --force', async () => {
    const output = tmpOutput();
    writeFileSync(output, 'keep me\n', 'utf8');
    const { code } = await run({ source: fixture('responses-3.1.yaml'), output, force: true });
    expect(code).toBe(0);
    expect(readFileSync(output, 'utf8')).toContain('resources:');
  });

  it('leaves no temporary file behind', async () => {
    const output = tmpOutput();
    await run({ source: fixture('responses-3.1.yaml'), output });
    const dir = join(output, '..');
    expect(readdirSync(dir)).toEqual(['out.yaml']);
  });

  it('applies --base-url over the document servers', async () => {
    const output = tmpOutput();
    const { code } = await run({
      source: fixture('relative-server.yaml'),
      output,
      baseUrl: 'https://backend.internal',
    });
    expect(code).toBe(0);
    expect(readFileSync(output, 'utf8')).toContain('url: https://backend.internal/a');
  });

  it('filters by --operation and fails on one that matched nothing', async () => {
    const output = tmpOutput();
    const kept = await run({
      source: fixture('responses-3.1.yaml'),
      output,
      operations: ['getOrder'],
    });
    expect(kept.code).toBe(0);
    const parsed = parseYaml(readFileSync(output, 'utf8')) as {
      resources: Record<string, unknown>;
    };
    expect(Object.keys(parsed.resources)).toEqual(['getOrder']);

    const missing = await run({
      source: fixture('responses-3.1.yaml'),
      output: tmpOutput(),
      operations: ['getOrder', 'nope'],
    });
    expect(missing.code).toBe(1);
    expect(missing.err).toContain('nope');
  });

  it('filters by --tag', async () => {
    const output = tmpOutput();
    await run({ source: fixture('responses-3.1.yaml'), output, tags: ['write'] });
    const parsed = parseYaml(readFileSync(output, 'utf8')) as {
      resources: Record<string, unknown>;
    };
    expect(Object.keys(parsed.resources)).toEqual(['cancelOrder']);
  });

  it('writes pricing only with --free and exposure only with --expose', async () => {
    const output = tmpOutput();
    const { out } = await run({
      source: fixture('responses-3.1.yaml'),
      output,
      free: true,
      expose: 'http, mcp',
    });
    const parsed = parseYaml(readFileSync(output, 'utf8')) as {
      resources: Record<string, { pricing: unknown; expose: unknown }>;
    };
    expect(parsed.resources['getOrder']?.pricing).toEqual({ type: 'free' });
    expect(parsed.resources['getOrder']?.expose).toEqual(['http', 'mcp']);
    expect(out).not.toContain('Pricing/exposure were not inferred.');
  });

  it('rejects an unsupported --expose protocol before reading the document', async () => {
    const output = tmpOutput();
    const { code, err } = await run({
      source: fixture('responses-3.1.yaml'),
      output,
      expose: 'http,htpp',
    });
    expect(code).toBe(1);
    expect(err).toContain('htpp');
    expect(err).toContain('http, mcp, a2a');
    expect(existsSync(output)).toBe(false);
  });

  it('turns warnings into a non-zero exit under --strict, writing nothing', async () => {
    const output = tmpOutput();
    const { code, err } = await run({
      source: fixture('responses-3.1.yaml'),
      output,
      strict: true,
    });
    expect(code).toBe(1);
    expect(err).toContain('--strict');
    expect(existsSync(output)).toBe(false);
  });

  it('emits a machine-readable summary with --json', async () => {
    const output = tmpOutput();
    const { code, out } = await run({
      source: fixture('responses-3.1.yaml'),
      output,
      json: true,
    });
    expect(code).toBe(0);
    const summary = JSON.parse(out) as {
      openapi: string;
      imported: number;
      warnings: number;
      output: string;
      resources: { id: string }[];
      diagnostics: { code: string }[];
      exitCode: number;
    };
    expect(summary.openapi).toBe('3.1');
    expect(summary.imported).toBe(5);
    expect(summary.output).toBe(output);
    expect(summary.resources.map((r) => r.id)).toContain('cancelOrder');
    expect(summary.diagnostics.some((d) => d.code === 'backend-authentication-required')).toBe(
      true,
    );
    expect(summary.exitCode).toBe(0);
  });

  it('fails when no supported operation could be imported', async () => {
    const output = tmpOutput();
    const { code, err } = await run({ source: fixture('relative-server.yaml'), output });
    expect(code).toBe(1);
    expect(err).toContain('no supported operations');
    expect(existsSync(output)).toBe(false);
  });

  it('reports an unreadable or invalid document without writing anything', async () => {
    const output = tmpOutput();
    const { code, err } = await run({ source: fixture('swagger-2.0.yaml'), output });
    expect(code).toBe(1);
    expect(err).toContain('Swagger 2.0');
    expect(existsSync(output)).toBe(false);
  });
});
