import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { runInit } from '../../../src/cli/commands/init.js';
import { defaultInitAnswers } from '../../../src/cli/lib/init-config.js';
import { createCapturingIo } from '../../../src/cli/lib/io.js';
import { CommerceError } from '../../../src/core/index.js';
import { makeGatewayConfig } from './fixtures.js';

function tmpConfigPath(): string {
  const dir = mkdtempSync(join(tmpdir(), 'agent-commerce-init-'));
  return join(dir, 'config.yaml');
}

describe('runInit — --yes (non-interactive, required for scripting/tests)', () => {
  it('writes a file that the real config loader accepts (end-to-end)', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io);

    expect(code).toBe(0);
    expect(existsSync(outputPath)).toBe(true);
    expect(io.out.join('\n')).toContain('PASS  Wrote');
    expect(io.out.join('\n')).toContain('is valid');
    expect(io.out.join('\n')).toContain('Next steps:');
  });

  it('refuses to overwrite an existing file without --force', async () => {
    const outputPath = tmpConfigPath();
    writeFileSync(outputPath, 'version: 1\n', 'utf8');
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io);

    expect(code).toBe(1);
    expect(io.err.join('\n')).toContain('already exists');
    // File must be untouched.
    expect(readFileSync(outputPath, 'utf8')).toBe('version: 1\n');
  });

  it('overwrites an existing file with --force', async () => {
    const outputPath = tmpConfigPath();
    writeFileSync(outputPath, 'version: 1\n', 'utf8');
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true, force: true }, io);

    expect(code).toBe(0);
    expect(readFileSync(outputPath, 'utf8')).toContain('Generated by `agent-commerce init`');
  });

  it('creates missing parent directories', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'agent-commerce-init-'));
    const outputPath = join(dir, 'nested', 'deeper', 'config.yaml');
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io);

    expect(code).toBe(0);
    expect(existsSync(outputPath)).toBe(true);
  });

  it('does not prompt interactively when --yes is set (collectAnswers is never invoked)', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();
    let called = false;

    await runInit({ outputPath, yes: true }, io, {
      collectAnswers: async () => {
        called = true;
        return defaultInitAnswers();
      },
    });

    expect(called).toBe(false);
  });
});

describe('runInit — validation failure is surfaced honestly', () => {
  it('exits non-zero and prints the formatted error when the generated config fails validation', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io, {
      loadConfig: async () => {
        throw new Error('simulated validation failure');
      },
    });

    expect(code).toBe(1);
    expect(io.err.join('\n')).toContain('simulated validation failure');
    // The answers validated in memory, so a failure reading the file back can
    // only be a renderer bug — and unlike the old blanket "report this as a
    // bug", that is now true when it is printed.
    expect(io.err.join('\n')).toContain('bug in the config renderer');
  });

  it('writes nothing when the answers themselves are invalid, and reports the real error', async () => {
    // Writing the file first, printing "PASS Wrote …", then loading it back
    // would tell the user to report their own input as a bug. Answers can
    // legitimately fail validation: an empty protocol multiselect, a typo'd
    // settlement address, a scheme-less backend URL.
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io, {
      parseConfig: async () => {
        throw new CommerceError('CONFIG_INVALID', 'resources.report.expose: too small');
      },
      loadConfig: async () => {
        throw new Error('must never be reached — nothing should have been written');
      },
    });

    expect(code).toBe(1);
    expect(existsSync(outputPath)).toBe(false);
    expect(io.out.join('\n')).not.toContain('Wrote');
    expect(io.err.join('\n')).toContain('resources.report.expose');
    expect(io.err.join('\n')).toContain('Nothing was written');
    expect(io.err.join('\n')).not.toContain('report this as a bug');
  });

  it('still reports PASS when the injected loader succeeds', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath, yes: true }, io, {
      loadConfig: async () => makeGatewayConfig(),
    });

    expect(code).toBe(0);
  });
});

describe('runInit — interactive path (collectAnswers injected)', () => {
  it('uses the collected answers to render the config', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath }, io, {
      collectAnswers: async () => ({
        backendBaseUrl: 'http://localhost:4000',
        resources: ['weather'],
        protocols: ['http'],
        x402Enabled: false,
        merchantPayTo: defaultInitAnswers().merchantPayTo,
      }),
      loadConfig: async () => makeGatewayConfig(),
    });

    expect(code).toBe(0);
    const written = readFileSync(outputPath, 'utf8');
    expect(written).toContain('localhost:4000');
    expect(written).not.toContain('report:');
  });

  it('aborts (exit 1, nothing written) when the user cancels', async () => {
    const outputPath = tmpConfigPath();
    const io = createCapturingIo();

    const code = await runInit({ outputPath }, io, {
      collectAnswers: async () => undefined,
    });

    expect(code).toBe(1);
    expect(existsSync(outputPath)).toBe(false);
    expect(io.err.join('\n')).toContain('aborted');
  });
});
