#!/usr/bin/env node
/**
 * Checks the semantic public contract surface: the resolved type of every
 * symbol src/core/public-types.ts exports, walked with the TypeScript API and
 * compared with docs/contract-surface.txt. Formatting, comments and import or
 * export order cannot change it; adding, removing or altering a type does.
 *
 *   node scripts/contract-surface.mjs           check against the baseline
 *   node scripts/contract-surface.mjs --write   re-baseline after an approved
 *                                               contract change
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = resolve(ROOT, 'src/core/public-types.ts');
const BASELINE = resolve(ROOT, 'docs/contract-surface.txt');

const program = ts.createProgram([ENTRY], {
  target: ts.ScriptTarget.ES2023,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  strict: true,
  exactOptionalPropertyTypes: true,
  noUncheckedIndexedAccess: true,
  skipLibCheck: true,
  noEmit: true,
});

const checker = program.getTypeChecker();
const source = program.getSourceFile(ENTRY);
if (!source) {
  console.error(`contract surface: cannot load ${ENTRY}`);
  process.exit(1);
}

const moduleSymbol = checker.getSymbolAtLocation(source);
if (!moduleSymbol) {
  console.error('contract surface: public-types.ts exports nothing');
  process.exit(1);
}

const FLAGS =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.WriteArrayAsGenericType |
  ts.TypeFormatFlags.UseFullyQualifiedType;

const lines = [];
for (const symbol of checker.getExportsOfModule(moduleSymbol)) {
  const target =
    symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  const declaration = target.declarations?.[0];

  let rendered;
  if (declaration && ts.isInterfaceDeclaration(declaration)) {
    const type = checker.getDeclaredTypeOfSymbol(target);
    const members = checker
      .getPropertiesOfType(type)
      .map((p) => {
        const decl = p.declarations?.[0];
        const propType = decl
          ? checker.typeToString(checker.getTypeOfSymbolAtLocation(p, decl), decl, FLAGS)
          : 'unknown';
        const optional = p.flags & ts.SymbolFlags.Optional ? '?' : '';
        const readonly = decl && ts.isPropertySignature(decl) &&
          decl.modifiers?.some((m) => m.kind === ts.SyntaxKind.ReadonlyKeyword)
            ? 'readonly '
            : '';
        return `    ${readonly}${p.getName()}${optional}: ${propType};`;
      })
      .sort();
    rendered = `interface ${symbol.getName()} {\n${members.join('\n')}\n  }`;
  } else if (declaration && ts.isTypeAliasDeclaration(declaration)) {
    rendered = `type ${symbol.getName()} = ${checker.typeToString(
      checker.getDeclaredTypeOfSymbol(target),
      declaration,
      FLAGS,
    )}`;
  } else if (declaration) {
    rendered = `value ${symbol.getName()}: ${checker.typeToString(
      checker.getTypeOfSymbolAtLocation(target, declaration),
      declaration,
      FLAGS,
    )}`;
  } else {
    rendered = `unknown ${symbol.getName()}`;
  }
  lines.push(rendered);
}

lines.sort();
const surface = `# Semantic surface of src/core/public-types.ts
# Generated by scripts/contract-surface.mjs - do not edit by hand.
# ${lines.length} exported symbols.

${lines.join('\n\n')}
`;

if (process.argv.includes('--write')) {
  writeFileSync(BASELINE, surface);
  console.log(`contract surface: baseline written (${lines.length} exported symbols).`);
  process.exit(0);
}

if (!existsSync(BASELINE)) {
  console.error('contract surface: no baseline. Run with --write to create one.');
  process.exit(1);
}

if (readFileSync(BASELINE, 'utf8') === surface) {
  console.log(`contract surface: OK, ${lines.length} exported symbols, unchanged.`);
  process.exit(0);
}

console.error('contract surface: the public contract CHANGED.');
console.error('');
console.error('A change here can break every consumer. Follow the change sequence at the');
console.error('top of docs/contracts.md and record it under "Recorded changes".');
console.error('Then re-baseline: node scripts/contract-surface.mjs --write');
console.error('');
console.error('Diff against the baseline:');
console.error('  node scripts/contract-surface.mjs --write && git diff docs/contract-surface.txt');
process.exit(1);
