/**
 * Canonical request/response model for the execution pipeline.
 *
 * FROZEN CONTRACT. Protocol adapters normalise into `CanonicalRequest` and map
 * `ExecutionOutcome` (or a thrown `CommerceError`) back into their own wire
 * format. Adapters must never call merchant backends directly.
 */
import type { AuthorizationRequirement, AuthorizationSubmission } from './authorization.js';
import type { IsoTimestamp, ProtocolName } from './common.js';
import type { PaymentRequirement, PaymentResult, PaymentSubmission } from './payment.js';
import type { CommerceReceipt } from './receipt.js';

export interface CanonicalRequest {
  /** Correlation id for the entire flow. Generated by the protocol adapter. */
  readonly requestId: string;
  readonly resourceId: string;
  /** Raw, unvalidated resource input. Validated against the resource schema. */
  readonly input: unknown;
  readonly protocol: ProtocolName;
  /** Payment proof, when the client is retrying after a challenge. */
  readonly payment?: PaymentSubmission;
  /**
   * Authorization proof, when the resource requires one. Independent of
   * `payment`: neither substitutes for the other, and a resource requiring
   * authorization needs both.
   */
  readonly authorization?: AuthorizationSubmission;
  readonly receivedAt: IsoTimestamp;
  /**
   * Stable name for the side-effecting operation this request performs, when
   * the protocol has one. Carried through to `BackendRequest` so the merchant
   * can recognise a retry as the same operation. Never `requestId`, which is
   * new on every call.
   */
  readonly idempotencyKey?: string;
  /** Non-secret transport metadata (client id, user agent, …). */
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/** Successful delivery of a resource. */
export interface DeliveredOutcome {
  readonly kind: 'delivered';
  readonly requestId: string;
  readonly resourceId: string;
  readonly backendStatus: number;
  readonly body: unknown;
  readonly headers?: Readonly<Record<string, string>>;
  readonly payment?: PaymentResult;
  readonly receipt: CommerceReceipt;
  readonly durationMs: number;
}

/** The resource costs money and no acceptable proof was supplied. */
export interface PaymentRequiredOutcome {
  readonly kind: 'payment-required';
  readonly requestId: string;
  readonly resourceId: string;
  readonly requirement: PaymentRequirement;
  /**
   * Authorization the buyer must also present on the retry, when the resource
   * requires one. Absent for the ordinary paid resource.
   */
  readonly authorization?: readonly AuthorizationRequirement[];
}

/**
 * Result of a pipeline execution.
 *
 * Every other condition (unknown resource, invalid input, rejected payment,
 * backend failure, storage failure) is signalled by throwing a `CommerceError`.
 */
export type ExecutionOutcome = DeliveredOutcome | PaymentRequiredOutcome;

/**
 * The single execution path every protocol adapter converges on.
 *
 * NOTE — two different signalling styles, deliberately:
 *
 * - `payment-required` is a normal RETURN VALUE (`PaymentRequiredOutcome`).
 * It is an expected step in the protocol, not a failure: the caller is
 * meant to read the challenge and retry with a proof.
 * - Everything else that goes wrong — including a *rejected* payment — is a
 * THROWN `CommerceError`.
 *
 * So `payment-required` and `payment-invalid` arrive through different
 * channels despite sounding symmetrical. Adapters must handle both:
 *
 * try {
 * const outcome = await pipeline.execute(request);
 * if (outcome.kind === 'payment-required') return toPaymentRequiredEnvelope(outcome);
 * return renderDelivered(outcome);
 * } catch (error) {
 * return toErrorEnvelope(toCommerceError(error));
 * }
 */
export interface ExecutionPipeline {
  execute(request: CanonicalRequest): Promise<ExecutionOutcome>;
}
